# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Platform_config = debug
  3D_Graphics_config = debug

else ifeq ($(config),release)
  Platform_config = release
  3D_Graphics_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Platform 3D-Graphics

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Platform:
ifneq (,$(Platform_config))
	@echo "==== Building Platform ($(Platform_config)) ===="
	@${MAKE} --no-print-directory -C App/src/platform -f Makefile config=$(Platform_config)
endif

3D-Graphics:
ifneq (,$(3D_Graphics_config))
	@echo "==== Building 3D-Graphics ($(3D_Graphics_config)) ===="
	@${MAKE} --no-print-directory -C App -f Makefile config=$(3D_Graphics_config)
endif

clean:
	@${MAKE} --no-print-directory -C App/src/platform -f Makefile clean
	@${MAKE} --no-print-directory -C App -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Platform"
	@echo "   3D-Graphics"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"